datastax/jvector

src/main/java/com/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, src/main/java/com/github/jbellis/jvector/vector/PanamaVectorizationProvider.java, src/main/java/com/github/jbellis/jvector/vector/SimdOps.java, src/main/java/com/github/jbellis/jvector/vector/VectorizationProvider.java, src/test/java/com/github/jbellis/jvector/graph/GraphIndexTestCase.java, src/test/java/com/github/jbellis/jvector/vector/TestVectorizationProvider.java
Bench Demo without and with Panama:
```
hdf5/nytimes-256-angular.hdf5: 289761 base and 9991 query vectors loaded, dimensions 256
Index   M=8 ef=60: top 100/1 recall 0.4346, build 18.34s, query 5.89s. 94003210 nodes visited
Index   M=8 ef=60: top 100/2 recall 0.5334, build 18.34s, query 10.87s. 160716180 nodes visited
Index   M=8 ef=60: top 100/4 recall 0.6192, build 18.34s, query 18.91s. 284583030 nodes visited
Index   M=8 ef=80: top 100/1 recall 0.4919, build 21.89s, query 5.99s. 100470940 nodes visited
Index   M=8 ef=80: top 100/2 recall 0.5919, build 21.89s, query 10.84s. 170832280 nodes visited
Index   M=8 ef=80: top 100/4 recall 0.6703, build 21.89s, query 19.76s. 300788670 nodes visited
hdf5/nytimes-256-angular.hdf5: 289761 base and 9991 query vectors loaded, dimensions 256
Index …
```
=> Add PanamaVectorSupport for Java 20+

.gitignore, README.md, pom.xml
Uses executions in both compile and jar tasks to do toggle which JVM is used. I most likely missed something, but the block and tackle stuff of compile and exec is working provided you follow the updated instructions in the readme. I'll add a section about how to reference the jar for the JDK version you want once I verify that with C*.
=> Issue 38 multiple jdk builds

jvector-base/src/main/java/io/github/jbellis/jvector/pq/CompressedDecoder.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/CompressedVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/ProductQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/DefaultVectorUtilSupport.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/DefaultVectorizationProvider.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtil.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtilSupport.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Bench.java, jvector-tests/src/test/java/io/github/jbellis/jvector/microbench/SimilarityBench.java, jvector-tests/src/test/java/io/github/jbellis/jvector/vector/TestVectorizationProvider.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorizationProvider.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
With this change the PQ goes from ~40% slower to ~20%
WITHOUT:
```
Wikipedia: 100000 base and 10000 query vectors loaded, dimensions 1536
PQ@384 build 43.81s,
PQ encode 3.28s,
Build M=8 ef=60 in 9.89s with 0.59 short edges
Query PQ=false top 101/1 recall 0.8925 in 18.69s after 18255466 nodes visited
Query PQ=true top 101/1 recall 0.8058 in 4.08s after 18507140 nodes visited
Query PQ=false top 101/2 recall 0.9439 in 4.38s after 31216274 nodes visited
Query PQ=true top 101/2 recall 0.9346 in 5.76s after 31572008 nodes visited
Build M=8 ef=80 in 11.92s with 0.63 short edges
Query PQ=false top 101/1 recall 0.8962 in 2.43s after 19259294 nodes visited
Query PQ=true top 101/1 recall 0.8074 in 3.69s after 19553584 nodes visited
Query PQ=false top 101/2 recall 0.9461 in 4.57s after 32799340 nodes …
```
=> Add simd approach for summing the cached PQ products of each encoded vector

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java
Since #117, `acceptOrds` should not be `null`. Instead, `Bits.ALL` should be used.
Also updated `GraphSearcher#search` javadoc to match implementation.
=> Fix usage of null acceptOrds in SiftSmall example

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeSimilarity.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Bench.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/IPCService.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/Test2DThreshold.java
Removing the overhead of reading all visited nodes' vectors and deserializing saves over 20% of query time pretty consistently.  The smaller topK is, the larger the win we expect (since the ratio of visited nodes to returned is higher).  These are the topK=100 results.
Before:
```
intfloat_e5-small-v2_100000: 100000 base and 10000 query vectors created, dimensions 384
Build M=16 ef=100 in 5.91s with avg degree 32.00 and 0.67 short edges
Uncompressed vectors
Query (memory) top 100/1 recall 0.8770 in 0.80s after 38,348,960 nodes visited
Query (disk) top 100/1 recall 0.8770 in 1.66s after 38,348,960 nodes visited
Query (memory) top 100/2 recall 0.9369 in 1.41s after 68,255,682 nodes visited
Query (disk) top 100/2 recall 0.9369 in 2.81s after 68,255,682 nodes visited
ProductQuantization(96) …
```
=> Remove caching of vectors encountered during search, update reranker interface accordingly

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java
`GraphIndexBuilder.addNNDescentConnections()` was being called serially for each effected node during cleanup after some nodes are marked as deleted.
When there are too many (like hundreds of thousands), `GraphIndexBuilder.cleanup()` was taking too much time, and most of it was in `removeDeletedNodes()` while calling `addNNDescentConnections()` in loop.
With this change `addNNDescentConnections()` is called in parallel using SIMD FJP.
=> Parallelize GraphIndexBuilder.removeDeletedNodes()

jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/GrowableBitSet.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/SynchronizedGrowableBitSet.java, jvector-tests/src/test/java/io/github/jbellis/jvector/util/TestSynchronizedGrowableBitSet.java
`GraphIndexBuilder.markNodeDeleted` uses `GrowableBitSet` as the backing storage to track deleted nodes. But since `GrowableBitSet` itself is not thread-safe, `markNodeDeleted` is not thread-safe either.
Added a synchronized version of `GrowableBitSet` and used it as the storage for deleted nodes.
_Currently `SynchronizedGrowableBitSet` uses a single lock to guard all access to `BitSet`. If more concurrency needed while deleting nodes, a lock-free & atomic version can be introduced._
Closes #174
=> Make GraphIndexBuilder.markNodeDeleted thread-safe

jvector-base/src/main/java/io/github/jbellis/jvector/util/DenseIntMap.java, jvector-tests/src/test/java/io/github/jbellis/jvector/util/TestDenseIntMap.java
`DenseIntMap.put()` was incrementing `size` field regardless of the operation is an insertion or an update.
Now it distinguishes inserts and updates by checking the old value.
=> Fix DenseIntMap size

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/ScoreTracker.java
just a nit, reducing number of objects created during search.
=> Don't create new ScoreTracker.NoOpTracker each time

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestDeletions.java
We might mark all nodes of the graph as deleted before calling cleanup.
Doing so causes graph's entry node to become unset(-1) after the `removeDeletedNodes` call in the `cleanup` method.
The rest of the cleanup logic expects a valid entry node for the graph to function correctly. Therefore, I added an early return to handle such a case.
=> Handle the case of removing all nodes in the cleanup

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java
Added that `GraphIndexBuilder#cleanup` should not be called concurrently with searches on graph.
Closes #188
=> Improve GraphIndexBuilder#cleanup doc for concurrent searches

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/GraphIndexBuilderTest.java
`connectToClosestNeighbor()` method looks like connecting a `neighborNode` to itself with the similarity score between `node` and `neighborNode`.
If I'm getting this logic correctly, it should connect `neighborNode` to `node` instead.
Closes #214
=> Fix GraphIndexBuilder.reconnectOrphanedNodes

jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java
the current path throws IO exception since there has been folder restructuring. Updated the path so SiftLoader.readFvecs does not throw FIleNotFound IO exception
=> Corrected relative path to access Siftsmall example files

jvector-base/src/main/java/io/github/jbellis/jvector/graph/ConcurrentNeighborSet.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeArray.java
this makes backlink() about 10% faster since most of its cost comes when it has to call removeAllNonDiverse
=> add a diverseBefore marker to avoid recomputing diversity that hasn't changed

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/InlineVectorValues.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/LvqVectorValues.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/ExceptionUtils.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/ExplicitThreadLocal.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java
I'm kind of on the fence here
I hate dancing with checked exceptions, but I do think it's a good thing to make GraphIndexBuilder more specific in its signature
=> GraphIndexBuilder implements Closeable instead of AutoCloseable

UPGRADING.md, jvector-base/src/main/java/io/github/jbellis/jvector/pq/BQVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/BinaryQuantization.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Bench.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/CompressorParameters.java, jvector-tests/src/test/java/io/github/jbellis/jvector/pq/TestCompressedVectors.java, jvector-tests/src/test/java/io/github/jbellis/jvector/pq/TestProductQuantization.java
First commit adds a test demonstrating that centering is counterproductive for BQ
Second commit removes BQ centering
I wasn't sure what to do about backwards compatibility but I decided to just ignore the centering from old BQ since if it's working at all it must be the case that your center is effectively zero anyway (which it is for our test datasets that are ~uniformly distributed across a unit hypersphere).
=> remove BQ centering

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/CommonHeader.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/Header.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/disk/TestOnDiskGraphIndex.java
getOffsetForOrdinal (renamed featureOffsetForOrdinal) needs to be aware that header size depends on version.
add testV0WriteIncremental to demonstrate the issue.
Least error-prone solution is to push size() into Header and CommonHeader.  This in turn means that MAGIC and versioning should be the responsibility of CommonHeader, rather than Header.
=> Fix writing jvector2-compatible indexes incrementally

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java
apply this to not relying on exceptions for SSP construction in Grid
(C* will use it too)
=> add getFeatureSet methods to ODGI and ODGIW

jvector-base/src/main/java/io/github/jbellis/jvector/graph/ConcurrentNeighborSet.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeArray.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/PQVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/ProductQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/ArrayByteSequence.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/ArrayVectorFloat.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/MemorySegmentByteSequence.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/MemorySegmentVectorFloat.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestConcurrentNeighborSet.java
commit 2 does most of the work, the key is that when insert() or insertDiverse() is called, we copy the source nodes into a size-limited NodeArray instead of assuming that the source array is correctly sized.  commit 2 also inlines and removes removeAllNonDiverse to improve clarity, that method was the only one related to diversity that did internal copies which was a bit confusing.
commit 3 does some fairly mechanical improvements of ramBytesUsed; most methods were not including object headers which for the ones where we have millions of instances (CNS and ArrayByteSequence) becomes material
=> improve memory usage during construction

jvector-base/src/main/java/io/github/jbellis/jvector/graph/ConcurrentNeighborMap.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeArray.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestNodeArray.java
Goal is to make it easier to audit ConcurrentNeighborMap to make sure we're not mutating the edge lists without copying first.
Did not see any violations of this rule but did fix a minor bug with insertNotDiverse as part of the first (size-related) commit, see the new assert.
(Builds on top of the rerank PR.)
=> Ecapsulate NodeArray internals

jvector-base/src/main/java/io/github/jbellis/jvector/disk/BufferedRandomAccessWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/disk/RandomAccessWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/Header.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/IPCService.java
ODGIW.path is removed
commentary on path removal:
OnDiskGraphIndexWriter wanted to own a raw Path to create its writer from because back when we thought we needed to rerank from disk during LTM construction, we'd use the Path to create a per-thread RandomAccessFile backing a custom FeatureSource.
Since then I think we came up with a cleaner solution, which is to call ODGI.writeHeader, and then open up a normal ODGI and use its read methods.
Besides being cleaner, this has the advantage of making during-construction reads use the same well-optimized path as other reads instead of being a special snowflake.
Finally, if this is wrong and we do in fact find a need to open additional handles against the output file in ODGIW, we could add a getPath method to the RandomAccessWriter interface and …
=> extract RandomAccessWriter interface from BRAW

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OrdinalMapper.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/disk/TestOnDiskGraphIndex.java
for the entry point test, I don't love adding a public method that should only be used by tests, I did it because
1. We want the test to access package-private code from OnDiskGraphIndexWriter (disk subpackage)
2. And also package-private code from GraphIndexBuilder
3. But I don't want to move either class to a different package
I'm open to a better solution.
=> Fixes for graphs with deletes

jvector-base/src/main/java/io/github/jbellis/jvector/pq/PQDecoder.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtil.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtilSupport.java, jvector-native/src/main/c/jvector_simd.c, jvector-native/src/main/c/jvector_simd.h, jvector-native/src/main/java/io/github/jbellis/jvector/vector/NativeVectorUtilSupport.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/cnative/NativeSimdOps.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
Fixes: https://github.com/jbellis/jvector/issues/367
=> Reenable SimdOps.assembleAndSum; implement Panama/Native equivalent for CosineDecoder acceleration

README.md, UPGRADING.md, jvector-base/src/main/java/io/github/jbellis/jvector/pq/BinaryQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/PQVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/ProductQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/pq/VectorCompressor.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/ArrayByteSequence.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/ArraySliceByteSequence.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/types/ByteSequence.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/IPCService.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/MemorySegmentByteSequence.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/NativeVectorUtilSupport.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestVectorGraph.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/disk/TestOnDiskGraphIndex.java, jvector-tests/src/test/java/io/github/jbellis/jvector/pq/TestADCGraphIndex.java, jvector-tests/src/test/java/io/github/jbellis/jvector/pq/TestCompressedVectors.java, jvector-tests/src/test/java/io/github/jbellis/jvector/pq/TestProductQuantization.java, jvector-tests/src/test/java/io/github/jbellis/jvector/vector/TestArraySliceByteSequence.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
The current design stores the compressed vectors using a list of `ByteSequence` objects where each object represents a single vector. That costs us an overhead of 16 bytes for the `ByteSequence` wrapper class and 16 more bytes for the array in the `ArrayByteSequence`. In the case of a 128 dimension vector, we compress PQ down to 64 bytes, so the cost of the wrapper/array is 32 bytes out of the total 96 bytes, which is 33% of the total size. In cases where we have many of these vectors in memory, an extra 33% is quite large.
This PR proposes removing the per-vector wrapper and opts for a more dense representation by
1. Storing the vectors in an array of ByteSequence references where the `ByteSequence` has as many vectors as it can possibly hold.
2. Introducing a `ByteSequence#slice` method …
=> Store compressed vectors in dense ByteSequence for PQVectors

jvector-tests/src/test/java/io/github/jbellis/jvector/microbench/SimilarityBench.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
This removes some data dependencies and permit much greater internal parallelism for the code.
On my machine this reduces the single-threaded dot product time for 1024 floats by one third, from 111 ns to 74 ns.
=> Hand-unroll the SIMD dot product loop

jvector-base/src/main/java/io/github/jbellis/jvector/quantization/BinaryQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/quantization/PQVectors.java
This resolves the issue that @jkni caught when reviewing #374. It renders the parallel vector accesses during "encodeAll" thread safe.
=> Make ravv usage thread-safe

jvector-native/src/main/java/io/github/jbellis/jvector/vector/VectorSimdOps.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
Fixes #385, which was caused by not using MemorySegmentVectorFloat.offset to compute the correct offset when loading a vector with FloatVector.fromMemorySegment. Also fixed a couple of bugs in the tail computations.
=> Fix distance computations in Native provider

jvector-tests/src/test/java/io/github/jbellis/jvector/graph/Test2DThreshold.java
This PR changes Test2DThreshold to control for:
- The average ratio between the number of visited nodes and the total number of nodes
- The average recall
This makes setting the thresholds easier and is more in line with the rest of tests in the library that also rely on averages (mean recall, for example).
=> Update Test2DThreshold to control for averages instead of worst-case statistics

README.md, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java
I noticed in the SiftSmall examples that when we demo persisting and loading back from disk we are still using the original flat vectors accessor which seem a bit counter intuitive since we are expecting OnDiskGraphIndex to already have the node vector values included.
https://github.com/jbellis/jvector/blob/main/jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java#L163
So in the example line above, should we switch this line: (using `raav` )
```java
Function<VectorFloat<?>, SearchScoreProvider> sspFactory = q -> SearchScoreProvider.exact(q, VectorSimilarityFunction.EUCLIDEAN, ravv);
```
To this (using the index view `index.getView()`):
```java
Function<VectorFloat<?>, SearchScoreProvider> sspFactory = q -> SearchScoreProvider.exact(q, …
```
=> make example use index view

.gitignore, benchmarks-jmh/README.md, benchmarks-jmh/pom.xml, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/RandomVectorsBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/StaticSetVectorsBenchmark.java, benchmarks-jmh/src/main/resources/log4j2.xml, pom.xml, rat-excludes.txt
This PR introduces a dedicated JMH benchmarking module (`benchmark-jmh`) to provide basic microbenchmarking for performance measurements for jvector operations. The module enables systematic performance testing and comparison of variants of the vector search such as:
- Search OnHeap/OnDisk 
- Random datasets vs static datasets.
- Search latency increase with dataset size
- Compare different scorer implementations
- Add new `benchmark-jmh` module
- Implement two sample JMH benchmarks for basic tests `RandomVectorsBenchmark` and `StaticSetVectorsBenchmark`
- Add logging configuration for benchmark execution
- Include benchmark documentation and usage instructions
- Uses JMH 1.37 for microbenchmarking with blackhole compiler settings
- Includes both throughput and average time measurements
- …
=> Add jmh benchmarks

jvector-base/src/main/java/io/github/jbellis/jvector/quantization/KMeansPlusPlusClusterer.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/DefaultVectorUtilSupport.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtil.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtilSupport.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/NativeVectorUtilSupport.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/VectorSimdOps.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
This PR optimizes the **io.github.jbellis.jvector.quantization.KMeansPlusPlusClusterer#chooseInitialCentroids** implementation using Java Vector API for the following cases.
1. Calculate minimums in a vectorized way instead of scalar fashion one at a time in loop.
2. Optimize scalar addition using vectorization. 
Tested the optimized code with the setup as below and observed latency reduction of ~6% in Product Quantization for ada002-100k dataset execution.
**Run Setup:**
**Jvector release used: 4.0.0-beta.1**
JDK used: 
**openjdk version "23.0.1" 2024-10-15**
OpenJDK Runtime Environment (build 23.0.1+11-39)
OpenJDK 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
Socket 1 of m7i.metal-48xl machine used
To check the benefit of this optimization reasonably, following changes were …
=> Optimization for latency reduction in Product Quantization

benchmarks-jmh/README.md, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/IndexConstructionWithStaticSetBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/PQBenchmark.java
This PR introduces two new JMH benchmarks:
1. IndexConstuctionBenchmark - `OnHeapGraphIndex` construction performance using the SIFT dataset.
2. PQBenchmark - for PQ compute performance evaluation
IndexConstructionBenchmark:
- `M`: Graph degree (values: 16, 32, 64)
- `beamWidth`: Search beam width (values: 10, 100)
PQBenchmark:
- `M`: Number of subspaces (values: 16, 32, 64)
```bash
mvn clean install -DskipTests=true
BENCHMARK_NAME="IndexConstructionWithStaticSetBenchmark"
java --enable-native-access=ALL-UNNAMED \
--add-modules=jdk.incubator.vector \
-XX:+HeapDumpOnOutOfMemoryError \
-Xmx14G -Djvector.experimental.enable_native_vectorization=true \
-jar benchmarks-jmh/target/benchmarks-jmh-4.0.0-beta.2-SNAPSHOT.jar $BENCHMARK_NAME
```
**IndexConstructionBenchmark**
Summary:
```shell …
```
=> add index construction benchmark

jvector-base/src/main/java/io/github/jbellis/jvector/quantization/PQDecoder.java, jvector-base/src/main/java/io/github/jbellis/jvector/quantization/PQVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/DefaultVectorUtilSupport.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtil.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtilSupport.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/NativeVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/SimdOps.java
With https://github.com/datastax/jvector/pull/370, I introduced the `ByteSequence::slice` method and started using it on the query path. The PR replaces long lived pq vector ByteSequences with short lived slices of larger ByteSequences created at query time. However, profiling reveals that these objects get created very often for certain workloads, especially brute force workloads in Cassandra. After analyzing the code, it looks trivial to migrate to a solution where we do not create a slice object per access to a pq vector. The main downside is the addition of an `offset` and a `length` argument to many methods and the fact that these changes feel brittle, if we want to maintain the `slice()` construct, which I think we do for the simplicity of non-query path code. However, given the …
=> Remove query-time usage of ByteSequence::slice in PQVectors to reduce object allocations

jvector-tests/src/test/java/io/github/jbellis/jvector/graph/Test2DThreshold.java, jvector-tests/src/test/java/io/github/jbellis/jvector/quantization/TestCompressedVectors.java
Two minor updates:
- In Test2DThreshold.testThreshold20k, use a more lenient threshold. The previous value was randomly failing (sometimes).
- In TestCompressedVectors.testNVQEncodings, remove the print statements that were polluting the console.
=> Fix flaky tests and eliminate console output

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Bench.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestVectorGraph.java
There were two bugs in the measurements in Bench:
1. The start time for measuring runtime was wrongly placed, so we were getting the wrong measurement for the second value in usePruningGrid. This bug caused to identify the use of search pruning (early termination) as a pessimization with the new hierarchical index, but the contrary is true. **We should enable search pruning by default**
2. The time was also the aggregate of both runs.
3. The reported node count was the aggregate of both runs through the queries. We are now correcting that.
This PR also changes returning the aggregate count of all queries to the average, which is more informative.
=> Search pruning & fix the reported number of visited nodes

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/feature/FusedADC.java
Addresses #416. The method FusedADC.writeInline was calling this [method](https://github.com/datastax/jvector/blob/41ce85d7efde7ff4893ee8258f89909d04e5aadb/jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java#L380). This small PR fixes the error.
=> Fix FusedADC.writeInline

benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/IndexConstructionWithStaticSetBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/PQBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/StaticSetVectorsBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Bench.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/AccuracyMetrics.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/DataSet.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/DataSetCreator.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/Hdf5Loader.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/util/SiftLoader.java
- Added the AccuracyMetrics class to have a single point where these computations happen. Easier to debug and reuse.
- Added mean average precision as an additional order-aware accuracy metric.
- Switched the ground truth from a List<Set<Integer>> to List<List<Integer>> to enable the computation of order-aware metrics like "n-recall@k" (see section 3.2 in [this paper](https://arxiv.org/pdf/2401.08281)) and mean average precision.
=> Rework the computation of accuracy

jvector-base/src/main/java/io/github/jbellis/jvector/graph/similarity/BuildScoreProvider.java
Addresses #418. It should help reduce the number of vector allocations during graph construction when using PQ compression
=> Reduce the number of vector allocations in BuildScoreProvider.pqBuilderScoreProvider

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java
When using a scoreProvider that does not have a reranker, GraphIndexBuilder.load was throwing a null pointer exception. This checks whether a reranker is available and use it. If not, it will use the primary score function.
=> Fix NPE in GraphIndexBuilder.load

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java
GraphIndex.size() is deprecated. It was returning size(0), but we should just call the method we want.
=> Fix calls to deprecated GraphIndex.size()

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestVectorGraph.java
Test resume was assuming a strict equivalence between a full search and a resumed search. Of course, they are not exactly equivalent, so we are relaxing the test to avoid flakiness in its output.
=> Update test resume

jvector-native/pom.xml
Fixes #429 
We won't get any more warning. See here, https://github.com/datastax/jvector/actions/runs/14383784844/job/40333969624?pr=430#step:6:8
=> bugfix for 429 - eliminate maven-resources-plugin warning

.github/workflows/tag-release.yml, CHANGELOG.md, rat-excludes.txt, update_changelog.sh
The idea is when [this GHA workflow](https://github.com/datastax/jvector/blob/main/.github/workflows/tag-release.yml) is manually kicked off, it will do 3 things:
1. Create a new tag based on the user input and push it to `main` branch
2. Update the changelog and automatically add the changes based on PRs merged with appropriate tags (sans any chore labels) and creates a PR to review and merge
3. Update the `pom.xml`'s *\<revision\>* tag to the next development version based on user's 2nd input
Today, there is no changelog and it is hard to understand what is available in a new tag release. This will make it easier for developers/viewers to look into the changelog file.
I hope this helps.
=> New GHA workflow to create new tag and update changelog

jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeQueue.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/AbstractLongHeap.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/BoundedLongHeap.java, jvector-base/src/main/java/io/github/jbellis/jvector/util/GrowableLongHeap.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestNodeQueue.java
- **Fix boundary check on BoundedLongHeap::pushAll**
Test added that fails without fix
- **Breaking change: refactor NodeScoreIterator**
The methods in the NodeScoreIterator
had opposite semantics from the NodeQueue.
One key problem was that nextScore
advanced the iterator. I propose instead
that we align with the NodeQueue names
and add topScore along with pop as the
key methods and pop will advance the
iterator. This is a breaking change
both in terms of the API and the semantics,
but because this interface was only
just released last week and we are
also breaking the compile-compatibility,
I view this as pretty low risk.
- **Fix missed requirement that heap is 1-based, not 0-based**
- **Rename pushAll to pushN to match actual semantics**
=> Fix/refactor NodeScoreIterator, BoundedLongHeap, and GrowableLongHeap bulk addition implementations

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndex.java
The method getNodes was using the maxDegree from the wrong layer to compute layer0NodeSize
=> Fix minor bug in OnDiskGraphIndex.getNodes

.github/workflows/tag-release.yml
This PR updates the GHA tag-release workflow to:
1. Fix the top-level POM version update to match tag-release
2. Reorder the tag and changelog steps so the changelog captures the latest changes
3. Create a second PR for the SNAPSHOT version bump
=> Fixes for GHA tag-release workflow

jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndex.java
This PR adds two small improvements:
1.  The methods OnDiskGraphIndex.View.getVector and OnDiskGraphIndex.View.getVectorInto shared a significant amount of code. This PR makes getVector call getVectorInto, simplifying the code to avoid potential errors.
2. The computation of the offsets for reading the file were (almost) duplicated in OnDiskGraphIndex.View.offsetFor and in OnDiskGraphIndex.View.neighborsOffsetFor. This PR refactors the computation so that the shared code goes into a common method.
=> Simplify OnDiskGraphIndex.View to avoid code duplication

jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/AccuracyBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/CountBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/ExecutionTimeBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/LatencyBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/ThroughputBenchmark.java
Improved setup for setting up which benchmark metrics to display when running Bench.
Now, we have two options:
1- Setting everything with the default format:
```
List<QueryBenchmark> benchmarks = List.of(
ThroughputBenchmark.createDefault(2, 0.1),
LatencyBenchmark.createDefault(),
CountBenchmark.createDefault(),
AccuracyBenchmark.createDefault(),
ExecutionTimeBenchmark.createDefault()
);
```
3- Setting everything from scratch:
```
List<QueryBenchmark> benchmarks = List.of(
ThroughputBenchmark.createDefault(2, 0.1)
.setFormat(".4f"),
LatencyBenchmark.createEmpty()
.displayAvgLatency(".4f")
.displayLatencySTD(".4f")
.displayP999Latency(".4f"),
CountBenchmark.createEmpty()
.displayAvgNodesVisited(".4f")
.displayAvgNodesExpanded(".4f")
.displayAvgNodesExpandedBaseLayer(".4f"), …
```
=> Better controls for setting string formats for the benchmark metrics

benchmarks-jmh/README.md, benchmarks-jmh/scripts/test_node_setup.sh, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/IndexConstructionWithRandomSetBenchmark.java, rat-excludes.txt
- Added setup scripts for node to run JMH benchmarks on.
- Added JMH for index buildup with random vectors
Testing was done on a GCP c-2 machine type.
=> Random vector index build jmh + setup scripts

jvector-base/src/main/java/io/github/jbellis/jvector/graph/ConcurrentNeighborMap.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/diversity/DiversityProvider.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/diversity/VamanaDiversityProvider.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestNeighbors.java
This PR does not change anything algorithmically but it separates the computation of diversity from the graph (i.e., ConcurrentNeighborMap). It is only meant to improve code clarity and separate responsibilities.
=> Factorize the computation of diverse edges

jvector-base/src/main/java/io/github/jbellis/jvector/graph/ConcurrentNeighborMap.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/NodeArray.java
Relates to https://github.com/riptano/cndb/issues/14077
I see a large number of allocations from within the `ConcurrentNeighborMap::insert` method. We can reduce some of these by finding the insertion point before copying the array.
Anecdotally, we hit this early exit code 54 times in the sift 10k vector dataset. I am not sure how representative this dataset is, but for such a minor code change, the optimization seems worth it.
=> Find insertion point before performing copy in ConcurrentNeighborMap

.github/workflows/unit-tests.yaml, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorizationProvider.java, jvector-native/pom.xml, jvector-native/src/main/c/jextract_vector_simd.sh, jvector-tests/src/test/java/io/github/jbellis/jvector/vector/TestVectorizationProvider.java, jvector-twenty/pom.xml
This completes bring-up of a test path for both panama and native test modes.
A summary of how it works:
* A separate arch-specific test matrix is run focusing only on ubuntu runners with avx512+ support
* The job verifies that the ISA has all the feature flags that are tested for in our native code stubs.
* GCC is installed, and the profiles which build the native library are used to build it fresh
* For native access mode (in Java 24)
* A single base test is run to ensure that the native provider is active with the command options.
* All tests in jvector-tests are run with the same options and assertion.
* For Panama mode (in java 20)
* A single base test is run to ensure that the panama provider is active with the given options.
* All tests in jvector-tests are run with the same …
=> avx512 test runners, jobs, and assertions

jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/similarity/BuildScoreProvider.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/similarity/DefaultSearchScoreProvider.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/similarity/ScoreFunction.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/similarity/SearchScoreProvider.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/IPCService.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/Test2DThreshold.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestVectorGraph.java
Adds a new method in GraphIndexBuilder to add a new graph node with the signature
` public long addGraphNode(int node, SearchScoreProvider searchScoreProvider)`
The search score provider needs to be compatible (as in yielding comparable distances) to the BuildScoreProvider provided in the constructor.
The rationale behind this new method is to avoid copies when working with systems that do not work with VectorFloat<?> internally. OpenSearch, for example.
Additionally, this PR changes the SearchScoreProvider final class into an interface. The goal is to add further flexibility in its implementation. The PR also adds a final class DefaultSearchScoreProvider that implements the interface.
=> Add a new graph node using a search score

jvector-multirelease/pom.xml, pom.xml
Reverts datastax/jvector#486
PR 486 introduced the changes needed to migrate from ossrh to sonatype central. However there was a plugin missed in the jvector-multirelease pom file so we need to revert and redo the release
=> Revert "Release 4.0.0 rc.1"

.github/workflows/generate-changelog.yaml
- Update permissions so bot can push branch.  Default permission is read.
- Tested on fork in repo mirroring our permissions.  Fixed the failure.
=> Allow generate-changelog GHA write permission for branch push

jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/QueryExecutor.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/ThroughputBenchmark.java
- Warmup now uses random vectors instead of a split of the test vectors
- In addition to Avg QPS, can report Median QPS and Max QPS
- Number of warmup and test passes is configurable
- Overloaded QueryExecutor to accept random vector queries
=> Improvements to throughput benchmark

benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/IndexConstructionWithRandomSetBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/PQDistanceCalculationBenchmark.java, jvector-base/src/main/java/io/github/jbellis/jvector/quantization/ImmutablePQVectors.java, jvector-base/src/main/java/io/github/jbellis/jvector/quantization/ProductQuantization.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/DefaultVectorUtilSupport.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtil.java, jvector-base/src/main/java/io/github/jbellis/jvector/vector/VectorUtilSupport.java, jvector-native/src/main/java/io/github/jbellis/jvector/vector/NativeVectorUtilSupport.java, jvector-tests/src/test/java/io/github/jbellis/jvector/quantization/TestProductQuantization.java, jvector-twenty/src/main/java/io/github/jbellis/jvector/vector/PanamaVectorUtilSupport.java
This pull request introduces significant improvements to the Product Quantization (PQ) codebase, primarily focused on enhancing support for similarity computations between quantized vectors and optimizing codebook partial sum calculations. The changes include new methods for calculating similarity using codebook partial sums, updates to benchmarks, and expanded tests to ensure correctness across similarity functions.
* Added a new method `createCodebookPartialSums` to `ProductQuantization`, enabling efficient computation of partial sums for codebook centroids and supporting multiple similarity functions (dot product, cosine, euclidean).
* Implemented and exposed `assembleAndSumPQ` in `VectorUtilSupport` and its implementations, allowing for fast similarity calculations between quantized …
=> Create partial sums for PQ codebook for use during diversity checks

.github/workflows/pr_checklist.md, CONTRIBUTIONS.md
This updates the PR checklist. It is more streamlined and compact.
=> streamline PR checklist

.github/workflows/run-bench.yml, jvector-examples/src/main/java/io/github/jbellis/jvector/example/AutoBenchYAML.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/ThroughputBenchmark.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/benchmarks/diagnostics/BenchmarkDiagnostics.java, jvector-examples/yaml-configs/datasets.yml
This PR addresses the following issues with the run-bench GitHub workflow for regression testing:
- Links benchmark_config input parameter to regression test arguments: This parameter was intended for use as a filter on the datasets to test with (e.g. provide a regex to run the regression tests on a subset of the default) but was not previously linked to the test execution so that all default datasets were tested regardless of the value of this argument
- Fixes issue where output files were not created when branch name contains an illegal character. Illegal characters will now be replaced with underscores in the filename.
- Fix for issue where report generation was not occurring in the final step because search for csv files was using an incorrect naming pattern.
- Fix for diagnostic …
=> Regression enhancements

benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/RecallWithRandomVectorsBenchmark.java, benchmarks-jmh/src/main/java/io/github/jbellis/jvector/bench/StaticSetVectorsBenchmark.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphIndexBuilder.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/ImmutableGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/MutableGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/AbstractGraphIndexWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/CommonHeader.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndex.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskGraphIndexWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/OnDiskSequentialGraphIndexWriter.java, jvector-base/src/main/java/io/github/jbellis/jvector/graph/disk/feature/FusedADC.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/Grid.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/IPCService.java, jvector-examples/src/main/java/io/github/jbellis/jvector/example/SiftSmall.java, jvector-tests/src/test/java/io/github/jbellis/jvector/TestUtil.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/GraphIndexBuilderTest.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestDeletions.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestVectorGraph.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/disk/TestOnDiskGraphIndex.java, jvector-tests/src/test/java/io/github/jbellis/jvector/graph/disk/TestOnDiskSequentialGraphIndexWriter.java, jvector-tests/src/test/java/io/github/jbellis/jvector/quantization/TestADCGraphIndex.java
The main intent of this PR is to add an interface in front of the OnHeapGraphIndex. This is because it has become clear recently that we will need new implementations for mutable graphs (that are more conservative in the use of heap memory). This PR paves the way towards that path.
Importantly, MutableGraphIndex is protected inside its package, because modifications should only be done through the GraphIndexBuilder class and never directly.
These changes triggered a lot of minor changes everywhere.
=> New MutableGraphIndex and ImmutableGraphIndex interfaces
